DROP DATABASE IF EXISTS TEMPOTRACK;

CREATE DATABASE IF NOT EXISTS TEMPOTRACK;

USE TEMPOTRACK;

CREATE TABLE IF NOT EXISTS USERS(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(200) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(200) NOT NULL
)Engine=InnoDB;


INSERT INTO USERS (FULL_NAME, USERNAME, PASSWORD) VALUES ('Kamlesh Baviskar', 'admin', '$2a$12$v83.UrGWUGf1.JWL8rb1ueXDefk.5LOQk4MbEs5zZMT0DGG8I6ymW');